[package]
name = "reversed-word-byte-rw"
version = "0.0.1"
edition = "2018"
authors = ["viv <vvnl+git@protonmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binread = "2.2.0"